+ ipn
hiqdev/omnipay-okpay pull request #2
Opened 2017-05-23 20:10 UTC by bladeroot

2017-05-23 20:16 UTC, SilverFire requested changes

2017-05-23 20:16 UTC, SilverFire commented on src/Message/PurchaseRequest.php
> +        // \yii\helpers\VarDumper::dump($this);die();
?

2017-05-23 20:17 UTC, hiqsol requested changes
Закоменченый код убери

2017-05-24 07:51 UTC, bladeroot commented on src/Message/PurchaseRequest.php
> +        // \yii\helpers\VarDumper::dump($this);die();
случайно оставил

2017-05-24 08:14 UTC, merged

2017-05-24 08:14 UTC, hiqsol commented
Про fees не понял, проясни.

2017-05-24 08:40 UTC, bladeroot commented
По fees - в соответствии с параметром определяется кто платит комиссию системы: получатель или плательщик
0 - получатель
1 - плательщик
Новая панелька не передавала параметр и соответственно комиссию платил получатель, в старой же передавался и соответственно платил плательщик